/** @format */

export const ActionTypes = {
  GET_LOCATIONS_LIST: 'GET_LOCATIONS_LIST',
  ON_LOCATION_SELECT: 'ON_LOCATION_SELECT',

  GET_CURRENT_CONDITIONS: 'GET_CURRENT_CONDITIONS',
  GET_FIVE_DAYS_FORECAST: 'GET_FIVE_DAYS_FORECAST',

  ADD_TO_FAVORITES: 'ADD_TO_FAVORITES',
  REMOVE_FROM_FAVORITES: 'REMOVE_FROM_FAVORITES',

  GET_DEGREE_UNIT: 'GET_DEGREE_UNIT',
  GET_DARK_MODE: 'GET_DARK_MODE',
};
